#!/bin/sh

# Move to Django App Folder
cd /var/django/app

# Remove Python Cache Files
find ./ -iname "*.pyc" -delete

# Django Collect Static
./manage.py collectstatic --noinput

# Django Makemigrations
./manage.py makemigrations

# Django Migrate
./manage.py migrate

# Django Test
./manage.py test --noinput

# Start Honcho
if [[ $1 == "server" ]]; then
	exec gunicorn -b [::]:8000 -k 'gevent' --timeout 120 -w ${WORKERS} ${APPNAME}.wsgi
fi

exec "$@"
