name: Pocketbase

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['pocketbase/**']
  # schedule:
  #   # Runs "At 04:05 on day-of-month 2." (see https://crontab.guru)
  #   - cron: '5 4 2 * *'

jobs:
  check:
    uses:  chinochao/docker-images/.github/workflows/r_check_tags_repo_vs_docker.yml@master
    with:
      repo_github: pocketbase/pocketbase
      repo_docker: chaudric/pocketbase

  build_scan_push:
    uses:  chinochao/docker-images/.github/workflows/r_build_scan_push.yml@master
    needs: check
    if: contains(needs.check.outputs.docker_version, needs.check.outputs.repo_version)
    with:
      directory: pocketbase
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}